Remove redundant minOccurs
buildingSMART/BCF-XML pull request #262
Opened 2020-12-08 04:13 UTC by ykulbak

2020-12-08 11:05 UTC, pasi-paasiala approved these changes
+1

2020-12-09 10:27 UTC, jasollien requested changes

2020-12-09 10:27 UTC, jasollien commented on Schemas/markup.xsd
>              <xs:element name="File" maxOccurs="unbounded">
Must also remove this

2020-12-09 10:27 UTC, jasollien commented on Schemas/markup.xsd
> +                                    maxOccurs="unbounded"/>
Why this line break?

2020-12-10 06:42 UTC, pasi-paasiala commented
This PR has extra commits. It should be rebased.

2020-12-10 07:17 UTC, pasi-paasiala approved these changes

2020-12-10 07:18 UTC, merged