Markup test cases
buildingSMART/BCF-XML pull request #287
Opened 2021-02-17 09:38 UTC by jasollien

2021-02-18 07:25 UTC, leosobral requested changes

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v3.0/Markup/Document Reference External/README.md
> +4. Verify that no information was lost during the export
missing dot at end of sentence

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v3.0/Markup/Document Reference External/README.md
> +---
Remove those lines below ..

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v2.1/Markup/Document Reference External/unzipped/extensions.xsd
> +        <User>jon.anders.sollien@catenda.no</User>
remove these real test users references

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v3.0/Markup/Due Date/README.md
> +1. Import _DueDate.bcf_.
Missing dots at end of all sentences for consistency

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v3.0/Markup/related topics with both topics in the same file/README.md
> +1. Import \case.bcf
Missing dots at end of bullet items

2021-02-18 07:25 UTC, leosobral commented on Test Cases/v3.0/Markup/related topics with both topics in the same file/README.md
> +> Verification paragrpah 2
typo on paragraph

2021-02-18 09:12 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/Document reference internal/unzipped/8ac9822a-761a-4deb-9f39-f61286acbf6a/markup.bcf
> +        <Files/>
Files is empty.

2021-02-18 09:13 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/Due Date/unzipped/fffc1b9d-1f64-46ee-ad84-4fd4a0640e5f/markup.bcf
> +        <Files/>
Files is empty

2021-02-18 09:14 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/Labels/unzipped/bee19eb8-3ec0-4e0d-90df-52afc806beaf/markup.bcf
> +        <Files/>
Files is empty

2021-02-18 09:14 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/Milestone/unzipped/547bb53e-0c84-4a07-a75d-19a68576394c/markup.bcf
> +        <Files/>
Files is empty

2021-02-18 09:15 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/User assignment/unzipped/7ad1a717-bf20-4c12-b511-cbd90370ddba/markup.bcf
> +        <Files/>
Files is empty.

2021-02-18 09:15 UTC, pasi-paasiala commented on Test Cases/v3.0/Markup/related topics with both topics in the same file/unzipped/a6f801b9-6bf6-4cb9-8b89-1ae24b76074a/markup.bcf
> +        <Files/>
Files is empty

2021-02-18 09:17 UTC, pasi-paasiala commented
extensions.xsd need to renamed to extensions.xml

2021-03-01 10:10 UTC, jasollien commented on Test Cases/v3.0/Markup/Due Date/unzipped/fffc1b9d-1f64-46ee-ad84-4fd4a0640e5f/markup.bcf
> +        <Files/>
Isn't that allowed?

2021-03-01 10:38 UTC, merged