BCF 3.0: Add test case for orthogonal camera
buildingSMART/BCF-XML pull request #289
Opened 2021-02-17 09:54 UTC by mattikannala

BCF 3.0: Add test case for orthogonal camera

2021-02-17 12:52 UTC, cschladetsch reviewed
Why do some bullet points end with punctuation and others not, and why the extra vertical whitespace for indented points.

2021-02-18 10:21 UTC, pasi-paasiala requested changes
extensions.xml is missing.

2021-02-18 10:35 UTC, mattikannala commented
> extensions.xml is missing.

added extensions.xml

2021-03-15 10:37 UTC, ykulbak approved these changes

2021-03-15 10:39 UTC, pasi-paasiala approved these changes

2021-03-15 10:39 UTC, merged