All components and spaces visible
buildingSMART/BCF-XML pull request #290
Opened 2021-02-17 09:56 UTC by ykulbak

2021-02-17 09:57 UTC, ykulbak commented
This test case should be tested in Bimsync and Solibri before its accepted.

2021-02-17 13:02 UTC, cschladetsch reviewed
Punctuation at end of paragraphs and bullet points is inconsistent.

Indented bullets are not indented.

2021-02-18 08:53 UTC, pasi-paasiala requested changes
-1

Detailed version must go. Imports fine otherwise.

2021-02-18 08:53 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/all components and spaces visible/unzipped/bcf.version
> +  <DetailedVersion>3.0</DetailedVersion>
Remove detailed version.

2021-02-18 11:01 UTC, ykulbak commented
@pasi-paasiala @jasollien ready for review. I've applied all comments

2021-03-15 09:57 UTC, pasi-paasiala approved these changes
+1

2021-03-15 10:43 UTC, merged