-Component selection
buildingSMART/BCF-XML pull request #291
Opened 2021-02-17 10:35 UTC by ykulbak

Should be tested with Solibri and bimsync

2021-02-17 12:54 UTC, cschladetsch reviewed
Punctuation at end of paragraphs and bullet points is inconsistent.

There is unneeded vertical white space.

2021-02-18 08:32 UTC, leosobral commented
Tested OK in Bimsync

2021-02-18 08:46 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Component selection/unzipped/bcf.version
> +  <DetailedVersion>3.0</DetailedVersion>
Remove detailed version

2021-02-18 08:48 UTC, pasi-paasiala requested changes
-1
Imports fine in Solibri. Detailed version needs to go.

2021-02-18 11:00 UTC, ykulbak commented
@pasi-paasiala @jasollien ready for review

2021-03-15 10:30 UTC, jasollien approved these changes

2021-03-15 10:34 UTC, merged