BCF 3.0: Add test case for single visible space
buildingSMART/BCF-XML pull request #293
Opened 2021-02-17 10:39 UTC by mattikannala

BCF 3.0: Add test case for single visible space

2021-02-17 12:49 UTC, cschladetsch reviewed
Why is there extra vertical whitespace around the indented bullet point? Should the indented bullet point end with a period?

2021-02-18 07:31 UTC, mattikannala commented
> Why is there extra vertical whitespace around the indented bullet point? Should the indented bullet point end with a period?

Don't know if it is now better. I tried to fix it.

2021-02-18 08:04 UTC, ykulbak approved these changes
Reviewed and tested on Aconex

2021-02-18 08:08 UTC, leosobral commented
Imports OK in Bimsync, but 3D viewer looks quite different with models loaded

2021-02-18 08:09 UTC, mattikannala commented
Renamed to lower "case single visible space.bcf"

2021-02-18 08:43 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Single visible space/unzipped/bcf.version
> +    <DetailedVersion>3.0</DetailedVersion>
Remove detailed version

2021-02-18 08:44 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Single visible space/unzipped/a3befb7d-8395-4e52-bbca-382fc4198217/markup.bcf
> +        <CreationAuthor>support@solibri.com</CreationAuthor>
Maybe use a generic email here.

2021-02-18 08:44 UTC, pasi-paasiala requested changes
-1

detailed version must go.

2021-02-18 09:35 UTC, mattikannala commented on Test Cases/v3.0/Visualization/Single visible space/unzipped/bcf.version
> +    <DetailedVersion>3.0</DetailedVersion>
Removed

2021-02-18 09:36 UTC, mattikannala commented on Test Cases/v3.0/Visualization/Single visible space/unzipped/a3befb7d-8395-4e52-bbca-382fc4198217/markup.bcf
> +        <CreationAuthor>support@solibri.com</CreationAuthor>
Changed to test@bcfxmltest.com

2021-02-18 10:32 UTC, mattikannala commented
added extensions.xml

2021-02-18 10:52 UTC, mattikannala commented
> -1
> 
> detailed version must go.

It is not there anymore.

2021-03-15 10:37 UTC, pasi-paasiala approved these changes
+2

2021-03-15 10:43 UTC, merged