Perspective camera
buildingSMART/BCF-XML pull request #295
Opened 2021-02-17 10:57 UTC by ykulbak

Requires testing with Solibri and Catenda

2021-02-17 12:37 UTC, cschladetsch commented
There are inconsistent line endings for `Test Cases/v3.0/Visualization/Perspective camera/README.md`. Some bullet points end in a full stop, others do not. Trivial, yes.

2021-02-18 08:09 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Perspective camera/unzipped/01777b21-ba39-4c2b-ad1d-a9320f81214a/formatted
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
Looks like an unnecessary file.

2021-02-18 08:10 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Perspective camera/unzipped/bcf.version
> +  <DetailedVersion>3.0</DetailedVersion>
Detailef version shouldn't be here.

2021-02-18 08:10 UTC, leosobral commented
Tested Ok in Bimsync, the red part of the snapshot image is not showing in Bimsync.

2021-02-18 08:11 UTC, pasi-paasiala requested changes
-1

2021-02-18 08:11 UTC, pasi-paasiala commented
Was able to read the BCF, but there are still some mistakes.

2021-02-18 11:13 UTC, ykulbak commented
> There are inconsistent line endings for `Test Cases/v3.0/Visualization/Perspective camera/README.md`. Some bullet points end in a full stop, others do not. Trivial, yes.
> 
> Also, do we want spaces in pathnames and should they have a mixed case?
> 
> For coders and cross-platform ease, the pathname `TestCases/v3.0/Visualization/PerspectiveCamera/Readme.md` would be preferred.
> 
> Unsure what the convention for README.md vs. Readme.md is.

@cschladetsch thanks for the comments. The file and directory naming conventions are as discussed an agreed with the group. I believe I fixed the inconsistencies in the README. 

@pasi-paasiala @jasollien review comments applied, please have a look

2021-03-15 13:08 UTC, CBenghi commented
Looks good to me.

2021-03-16 07:52 UTC, CBenghi approved these changes

2021-03-16 07:54 UTC, pasi-paasiala approved these changes

2021-03-16 07:54 UTC, merged