Single visible wall test case
buildingSMART/BCF-XML pull request #296
Opened 2021-02-18 07:27 UTC by ykulbak

2021-02-18 08:24 UTC, leosobral commented
Tested Ok in Bimsync

2021-02-18 08:36 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Single visible wall/unzipped/bcf.version
> +  <DetailedVersion>3.0</DetailedVersion>
Remove detailed version

2021-02-18 08:39 UTC, pasi-paasiala requested changes
-1

Imports fine in Solibri, some minor things.

2021-02-18 08:39 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/Single visible wall/README.md
> +# \<Single invisible wall\>
Should this be 'visible' instead

2021-02-18 11:21 UTC, ykulbak commented
@pasi-paasiala @jasollien I've applied the review comments please check

2021-03-15 09:49 UTC, pasi-paasiala approved these changes
+1

2021-03-15 09:50 UTC, merged