BCF 3.0: Add test case for all parts of decomposed object except one visible
buildingSMART/BCF-XML pull request #299
Opened 2021-02-18 07:59 UTC by mattikannala

BCF 3.0: Add test case for all parts of decomposed object except one visible

2021-02-18 08:12 UTC, ykulbak approved these changes
Changed reviewed and tested on Aconex

2021-02-18 08:14 UTC, pasi-paasiala requested changes
-1

At least detailed version needs to go.

2021-02-18 08:14 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/28942812-8783-4d92-9c54-8a8f31937975/markup.bcf
> +        <CreationAuthor>support@solibri.com</CreationAuthor>
Should we use some other email here?

2021-02-18 08:14 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/bcf.version
> +    <DetailedVersion>3.0</DetailedVersion>
Detailed version need to be removed.

2021-02-18 08:23 UTC, leosobral commented
Tested OK in Bimsync

2021-02-18 09:28 UTC, mattikannala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/28942812-8783-4d92-9c54-8a8f31937975/markup.bcf
> +        <CreationAuthor>support@solibri.com</CreationAuthor>
Changed to test@bcfxmltest.com

2021-02-18 09:28 UTC, mattikannala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/bcf.version
> +    <DetailedVersion>3.0</DetailedVersion>
Removed

2021-02-18 10:12 UTC, pasi-paasiala requested changes
extensions.xml needs to be added.

2021-02-18 10:12 UTC, pasi-paasiala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/project.bcfp
> +    <ExtensionSchema></ExtensionSchema>
This line needs to go.

2021-02-18 10:51 UTC, mattikannala commented on Test Cases/v3.0/Visualization/All parts of decomposed object except one visible/unzipped/project.bcfp
> +    <ExtensionSchema></ExtensionSchema>
The file is not more

2021-03-15 09:41 UTC, pasi-paasiala commented
> extensions.xml needs to be added.

This is now fixed

2021-03-15 09:41 UTC, pasi-paasiala approved these changes
+2

2021-03-15 10:27 UTC, merged